<!DOCTYPE html><html lang="de-ch"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Java basics: Exceptions - Finecloud</title><meta name="description" content="What are Exceptions? An exception is an event, commonly it is a problem that arises during the execution of a program. When an Exception occurs the normal program is disrupted and the program/Application terminates abnormally, which is not recommended. Unexpected termination of an Application is&hellip;"><meta name="generator" content="Publii Open-Source CMS for Static Site"><link rel="canonical" href="https://www.finecloud.ch/java-exceptions.html"><link rel="alternate" type="application/atom+xml" href="https://www.finecloud.ch/feed.xml"><link rel="alternate" type="application/json" href="https://www.finecloud.ch/feed.json"><meta property="og:title" content="Java basics: Exceptions"><meta property="og:site_name" content="Finecloud"><meta property="og:description" content="What are Exceptions? An exception is an event, commonly it is a problem that arises during the execution of a program. When an Exception occurs the normal program is disrupted and the program/Application terminates abnormally, which is not recommended. Unexpected termination of an Application is&hellip;"><meta property="og:url" content="https://www.finecloud.ch/java-exceptions.html"><meta property="og:type" content="article"><link rel="shortcut icon" href="https://www.finecloud.ch/media/website/finecloud.png" type="image/png"><link rel="stylesheet" href="https://www.finecloud.ch/assets/css/style.css?v=7c7ed2e3e90182a09465f36ea7129616"><script type="application/ld+json">{"@context":"http://schema.org","@type":"Article","mainEntityOfPage":{"@type":"WebPage","@id":"https://www.finecloud.ch/java-exceptions.html"},"headline":"Java basics: Exceptions","datePublished":"2022-08-23T10:05","dateModified":"2022-08-23T12:05","description":"What are Exceptions? An exception is an event, commonly it is a problem that arises during the execution of a program. When an Exception occurs the normal program is disrupted and the program/Application terminates abnormally, which is not recommended. Unexpected termination of an Application is&hellip;","author":{"@type":"Person","name":"Finecloud","url":"https://www.finecloud.ch/authors/finecloud/"},"publisher":{"@type":"Organization","name":"Finecloud"}}</script><meta name="google-site-verification" content="seFY9U12uiEq5U3_MyZiX6XWzk0AVFl9zITr2ZKsytY"></head><body><div class="site-container"><header class="top" id="js-header"><a class="logo" href="https://www.finecloud.ch/">Finecloud</a><nav class="navbar js-navbar"><button class="navbar__toggle js-toggle" aria-label="Menu" aria-haspopup="true" aria-expanded="false"><span class="navbar__toggle-box"><span class="navbar__toggle-inner">Menu</span></span></button><ul class="navbar__menu"><li><a href="https://www.finecloud.ch/" target="_self">Blog</a></li><li><a href="https://www.finecloud.ch/tags/" target="_self">Tags</a></li></ul></nav><div class="search"><div class="search__overlay js-search-overlay"><div class="search__overlay-inner"><form action="https://www.finecloud.ch/search.html" class="search__form"><input class="search__input js-search-input" type="search" name="q" placeholder="search..." aria-label="search..." autofocus="autofocus"></form><button class="search__close js-search-close" aria-label="Close">Close</button></div></div><button class="search__btn js-search-btn" aria-label="Search"><svg role="presentation" focusable="false"><use xlink:href="https://www.finecloud.ch/assets/svg/svg-map.svg#search"/></svg></button></div></header><main><article class="post"><div class="hero"><figure class="hero__image hero__image--overlay"><img src="https://www.finecloud.ch/media/website/download.jpg" srcset="https://www.finecloud.ch/media/website/responsive/download-xs.jpg 300w, https://www.finecloud.ch/media/website/responsive/download-sm.jpg 480w, https://www.finecloud.ch/media/website/responsive/download-md.jpg 768w, https://www.finecloud.ch/media/website/responsive/download-lg.jpg 1024w, https://www.finecloud.ch/media/website/responsive/download-xl.jpg 1360w, https://www.finecloud.ch/media/website/responsive/download-2xl.jpg 1600w" sizes="100vw" loading="eager" alt=""></figure><header class="hero__content"><div class="wrapper"><div class="post__meta"><time datetime="2022-08-23T10:05">August 23, 2022</time></div><h1>Java basics: Exceptions</h1></div></header></div><div class="wrapper post__entry"><div class="post__toc"><h3>Table of Contents</h3><ul><li><a href="#mcetoc_1gb4ofck08p">What are Exceptions?</a></li><li><a href="#mcetoc_1gb4ofck08q">Types of Exceptions</a></li><li><a href="#mcetoc_1gb4ofck08r">Example Scenario #1</a></li><li><a href="#mcetoc_1gb4p2t6m8t">Try / Catch</a></li><li><a href="#mcetoc_1gb4q077394">The Exception</a></li><li><a href="#mcetoc_1gb4ofck08r">Example ScenarioÂ #2</a></li><li><a href="#mcetoc_1gb4rqeac9d">Multiple catches</a></li><li><a href="#mcetoc_1gb4uonu7kt">Stack Trace</a></li><li><a href="#mcetoc_1gb4uonu7ku">Runtime Exceptions</a></li><li><a href="#mcetoc_1gb521do8qr">Checked Exceptions</a></li><li><a href="#mcetoc_1gb521do8qs">Finally</a></li><li><a href="#mcetoc_1gb521do8qt">Optimizing Example Szenario #1</a></li></ul></div><h2 id="mcetoc_1gb4ofck08p">What are Exceptions?</h2><p>An exception is an event, commonly it is a problem that arises during the execution of a program. When an Exception occurs the normal program is disrupted and the program/Application terminates abnormally, which is not recommended. Unexpected termination of an Application is never wanted and this is why exceptions should be handled, so that the Application lets the User know that some Error or Problem exists, but the Application itself should not just die without any information.</p><p>The most common scenarios where an exception occurs are:</p><ul><li>the user entered invalid data</li><li>a file needs to be opened but cannot be found</li><li>a network connection has been lost during communication</li><li>the JVM has run out of memory</li></ul><h2 id="mcetoc_1gb4ofck08q">Types of Exceptions</h2><p>There are three main types of Java Exceptions:</p><ul><li>Checked Exceptions</li><li>Runtime Exceptions</li><li>Error Exceptions</li></ul><p>Checked and Runtime Exceptions both extend the same superclass, which is Exception. Exception class itself extends from a superclass called Throwable.</p><h2 id="mcetoc_1gb4ofck08r">Example Scenario #1</h2><p>Given the following code:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">int</span> num = 0;
        System.out.println(array.length / num);
        System.out.println(array[2]);
    }
}
</pre><p>if we execute this application it crashes like this:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">Exception in thread <span class="hljs-string" style="color: #6a8759;">"main"</span> java.lang.ArithmeticException: / by zero
	at section11_loose_ends.ExceptionTests.main(ExceptionTests.java:<span class="hljs-number" style="color: #6897bb;">7</span>)

Process finished with exit code <span class="hljs-number" style="color: #6897bb;">1</span></pre><p>this should not be surprising, since the fact that a devision by zero is considered to be impossible. <span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);">And so the JVM generated this arithmetic exception. </span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);">And what happens then is that once we get to this line in that arithmetic exception is thrown. </span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);">The program just dies.</span></p><p><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);">ðŸ’€</span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);"> Right then and there.</span></p><p>So line six is never even reached because that exception got thrown.</p><h2 id="mcetoc_1gb4p2t6m8t">Try / Catch</h2><p><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);" data-purpose="cue-text">What we will do next here is really just for illustrative purposes. </span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);" data-purpose="cue-text">This this isn't actually, generally speaking, a good idea, but we</span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);"> can handle this exception or we can catch this particular exception like this:</span></p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">int</span> num = <span class="hljs-number" style="color: #6897bb;">0</span>;
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            System.out.println(array.length / num);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (Exception e) {
            e.printStackTrace();
        }
        System.out.println(array[<span class="hljs-number" style="color: #6897bb;">2</span>]);
    }
</pre><div class="transcript--cue-container--wu3UY"><div class="transcript--cue-container--wu3UY"><p class="transcript--underline-cue--3osdw" tabindex="-1" role="button" data-purpose="transcript-cue"><span data-purpose="cue-text">This is called a try catch block. </span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);">So now we've got this keyword try. </span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);">So we're now telling the JVM essentially try executing this line. </span><span style="color: var(--text-primary-color); font-family: var(--editor-font-family); font-size: inherit; font-weight: var(--font-weight-normal);">And if anything goes wrong, maybe we'll catch it and do something about it down here.</span></p></div><div class="transcript--cue-container--wu3UY"><p class="transcript--underline-cue--3osdw" tabindex="-1" role="button" data-purpose="transcript-cue"><span data-purpose="cue-text">So now if I run this again, let's see what happens:</span></p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">java.lang.ArithmeticException: / by zero
	at section11_loose_ends.ExceptionTests.main(ExceptionTests.java:<span class="hljs-number" style="color: #6897bb;">8</span>)
three

Process finished with exit code <span class="hljs-number" style="color: #6897bb;">0</span></pre><p tabindex="-1" role="button" data-purpose="transcript-cue">So we still have an exception happening here. The divide by zero, but the next line line 10 is executing now. Please note, this is generally not a good idea, this is just for illustrative purposes so that you can learn how exceptions work and how they can be caught and when to catch them and how and why, and all of that.<br><br>So what just happened now is that an exception was still generated in throne when the JVM realised that we were about to attempt a divide by zero operation here. So it generated the arithmetic exception and it threw it. But now that we have this try catch block here, we cut the exception. And so that's why they used these terms to throw and to catch right.</p><h2 id="mcetoc_1gb4q077394" tabindex="-1" role="button" data-purpose="transcript-cue">The Exception</h2><p tabindex="-1" role="button" data-purpose="transcript-cue">You can think of it as an object, it's an object that's sort of being thrown. And if you set up a catcher to catch it, then you can do something sometimes with that exception. In this particular case, all we're doing with it is simply printing its stack trace. Basically, it's printing the details of the error that occurred. And that's how we get to see this divide by zero.<br><br>Now, previously, before I surrounded this line with a try catch, we were still seeing this, this output here, and that was happening because the exception was being handled by the JVM itself. Beyond the main method here, we're doing all of this inside of one main method. Something called the main method, though. And so what happened before we had this try catch block here is that the exception was thrown and it made its way outside of the main method. And then the JVM were the thing that called our main method handled it. And in its handling of the method, it displayed the stack trace just like we're doing now.<br><br>Now, because we are now handling this method with try and catch here, as soon as we call the division by zero line, the App does not crash because we're handling it and we're not killing the application as a result of it. This allows us to proceed to the next line and print the array content.</p><p tabindex="-1" role="button" data-purpose="transcript-cue">But in this particular case, it's not really a good idea at all, because with this divide by zero happening here, we're not able to fix anything. All we're doing is just saying, Oh yeah, that divide by zero occurred. Let's move on. It's kind of like if your house was on fire and you're driving by and you see your house is on fire and you say, Oh, look, my house is on fire and then you just keep driving. ðŸ”¥</p><p tabindex="-1" role="button" data-purpose="transcript-cue"><strong>We are not really handling the exception in any way.</strong><br><br>All I'm doing is just noting yet there's that exception and I'm printing it out. Oftentimes, the better thing to do in a case like this might be to just let the program die, which would be the default behavior of the JVM.</p><h2 id="mcetoc_1gb4ofck08r">Example ScenarioÂ #2</h2><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">int</span> num = <span class="hljs-number" style="color: #6897bb;">1</span>;
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            System.out.println(array.length / num);
            System.out.println(array[<span class="hljs-number" style="color: #6897bb;">3</span>]);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (ArrayIndexOutOfBoundsException e) {
            System.out.println(<span class="hljs-string" style="color: #6a8759;">"The array index was thrown here"</span>);
        }
        System.out.println(<span class="hljs-string" style="color: #6a8759;">"You made it to the end"</span>);
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">output:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-number" style="color: #6897bb;">3</span>
The array index was thrown here
You made it to the end

Process finished with exit code <span class="hljs-number" style="color: #6897bb;">0</span></pre><p tabindex="-1" role="button" data-purpose="transcript-cue">So we are able to say what these catch blocks here, what type of exception we are expecting to catch and then do something accordingly to that. In this example we have something called array index out of bounds exception. So this is a subclass of exception. And one interesting thing we can do with this is we could actually be much more specific in what exception we're actually looking for here.<br><br>So what happens if we change <em>num</em> back to zero?</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">int</span> num = 0;
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            System.out.println(array.length / num);
            System.out.println(array[<span class="hljs-number" style="color: #6897bb;">3</span>]);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (ArrayIndexOutOfBoundsException e) {
            System.out.println(<span class="hljs-string" style="color: #6a8759;">"The array index was thrown here"</span>);
        }
        System.out.println(<span class="hljs-string" style="color: #6a8759;">"You made it to the end"</span>);
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">output:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">Exception in thread <span class="hljs-string" style="color: #6a8759;">"main"</span> java.lang.ArithmeticException: / by zero
	at section11_loose_ends.ExceptionTests.main(ExceptionTests.java:<span class="hljs-number" style="color: #6897bb;">8</span>)

Process finished with exit code <span class="hljs-number" style="color: #6897bb;">1</span></pre><p tabindex="-1" role="button" data-purpose="transcript-cue">So now we're getting an exception here, and it's the familiar divide by zero exception, which is an arithmetic exception. We're not even making it to the end of the program anymore, even though we've got to try catch block,Â  we're not making it to the end of the program anymore. And the reason for that is because we are no longer catching this arithmetic exception.</p><p tabindex="-1" role="button" data-purpose="transcript-cue"><strong>Well, we never were catching an arithmetic exception. Initially, we were catching just an exception. And now we're catching an array index out of bounds exception. However, since arithmetic exception and array index out of bounds exception, both extend from exception. And we were explicitly catching exception. That catch was handling both types and so many more, by the way.Â  You can always catch the more generic exception data type.</strong><br><br>Sometimes it can also be a bad thing if you're not aware that that could be happening in general. You do actually want to catch the most specific exception data type that is meaningful for whatever it is that you're doing.</p><h2 id="mcetoc_1gb4rqeac9d" tabindex="-1" role="button" data-purpose="transcript-cue">Multiple catches</h2><p tabindex="-1" role="button" data-purpose="transcript-cue">We can actually specify multiple catches:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">int</span> num = <span class="hljs-number" style="color: #6897bb;">0</span>;
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            System.out.println(array.length / num);
            System.out.println(array[<span class="hljs-number" style="color: #6897bb;">3</span>]);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (ArrayIndexOutOfBoundsException e) {
            System.out.println(<span class="hljs-string" style="color: #6a8759;">"The array index was thrown here"</span>);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (ArithmeticException e) {
            System.out.println(<span class="hljs-string" style="color: #6a8759;">"This is due to the arithmetic exception being thrown"</span>);
        }
        System.out.println(<span class="hljs-string" style="color: #6a8759;">"You made it to the end"</span>);
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">output:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">This is due to the arithmetic exception being thrown
You made it to the end

Process finished with exit code <span class="hljs-number" style="color: #6897bb;">0</span></pre><p tabindex="-1" role="button" data-purpose="transcript-cue">Because we are now handling that exception with this explicit catch here, the program in this case isn't dying. So in general, you can have as many catches as you need to handle, whatever the situations are.<br><br>What if we wanted to do basically the same error handling for both for either of these catches? Sure we just copy-paste the same code for both catches, but you always want to eliminate duplicate code, so we need to consolidate this because otherwise we have duplicated code. So what we can do is actually combine these two bits into one catch block here, and the way we can do that is simply within order. This is called multi-catch:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">int</span> num = <span class="hljs-number" style="color: #6897bb;">0</span>;
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            System.out.println(array.length / num);
            System.out.println(array[<span class="hljs-number" style="color: #6897bb;">3</span>]);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (ArrayIndexOutOfBoundsException | ArithmeticException e ) {
            System.out.printf(<span class="hljs-string" style="color: #6a8759;">"Exception type: %s. Message: %s%n"</span>, e.getClass(), e.getMessage());
            e.printStackTrace();
        }
        System.out.println(<span class="hljs-string" style="color: #6a8759;">"You made it to the end"</span>);
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">output:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">Exception type: <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">java</span>.<span class="hljs-title" style="color: #ffc66d;">lang</span>.<span class="hljs-title" style="color: #ffc66d;">ArithmeticException</span>. <span class="hljs-title" style="color: #ffc66d;">Message</span>: / <span class="hljs-title" style="color: #ffc66d;">by</span> <span class="hljs-title" style="color: #ffc66d;">zero</span>
<span class="hljs-title" style="color: #ffc66d;">You</span> <span class="hljs-title" style="color: #ffc66d;">made</span> <span class="hljs-title" style="color: #ffc66d;">it</span> <span class="hljs-title" style="color: #ffc66d;">to</span> <span class="hljs-title" style="color: #ffc66d;">the</span> <span class="hljs-title" style="color: #ffc66d;">end</span>
<span class="hljs-title" style="color: #ffc66d;">java</span>.<span class="hljs-title" style="color: #ffc66d;">lang</span>.<span class="hljs-title" style="color: #ffc66d;">ArithmeticException</span>: / <span class="hljs-title" style="color: #ffc66d;">by</span> <span class="hljs-title" style="color: #ffc66d;">zero</span>
	<span class="hljs-title" style="color: #ffc66d;">at</span> <span class="hljs-title" style="color: #ffc66d;">section11_loose_ends</span>.<span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span>.<span class="hljs-title" style="color: #ffc66d;">main</span>(<span class="hljs-title" style="color: #ffc66d;">ExceptionTests</span>.<span class="hljs-title" style="color: #ffc66d;">java</span>:8)

<span class="hljs-title" style="color: #ffc66d;">Process</span> <span class="hljs-title" style="color: #ffc66d;">finished</span> <span class="hljs-title" style="color: #ffc66d;">with</span> <span class="hljs-title" style="color: #ffc66d;">exit</span> <span class="hljs-title" style="color: #ffc66d;">code</span> 0</span></pre><p tabindex="-1" role="button" data-purpose="transcript-cue">That's at least giving us a little bit more of a hint of what exactly went wrong. Especially since now we're handling it all in the same code with the same single catch.Â </p><h2 id="mcetoc_1gb4uonu7kt" tabindex="-1" role="button" data-purpose="transcript-cue">Stack Trace</h2><p tabindex="-1" role="button" data-purpose="transcript-cue">So let's talk a little bit more about the Stack Trace business now. What if we create a new method with all of that code in it? All the try catch business like before, but our main method is still going to be the starting point into our program. So the main method is going to start up and we're going to call this second level method:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v2</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        doSecondLevel();
        System.out.println(<span class="hljs-string" style="color: #6a8759;">"You made it to the end"</span>);
    }

    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">private</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">doSecondLevel</span><span class="hljs-params">()</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">int</span> num = <span class="hljs-number" style="color: #6897bb;">0</span>;
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            System.out.println(array.length / num);
            System.out.println(array[<span class="hljs-number" style="color: #6897bb;">3</span>]);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (ArrayIndexOutOfBoundsException | ArithmeticException e ) {
            System.out.printf(<span class="hljs-string" style="color: #6a8759;">"Exception type: %s. Message: %s%n"</span>, e.getClass(), e.getMessage());
            e.printStackTrace();
        }
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">let's run this and see what what we get here:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">Exception type: <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">java</span>.<span class="hljs-title" style="color: #ffc66d;">lang</span>.<span class="hljs-title" style="color: #ffc66d;">ArithmeticException</span>. <span class="hljs-title" style="color: #ffc66d;">Message</span>: / <span class="hljs-title" style="color: #ffc66d;">by</span> <span class="hljs-title" style="color: #ffc66d;">zero</span>
<span class="hljs-title" style="color: #ffc66d;">You</span> <span class="hljs-title" style="color: #ffc66d;">made</span> <span class="hljs-title" style="color: #ffc66d;">it</span> <span class="hljs-title" style="color: #ffc66d;">to</span> <span class="hljs-title" style="color: #ffc66d;">the</span> <span class="hljs-title" style="color: #ffc66d;">end</span>
<span class="hljs-title" style="color: #ffc66d;">java</span>.<span class="hljs-title" style="color: #ffc66d;">lang</span>.<span class="hljs-title" style="color: #ffc66d;">ArithmeticException</span>: / <span class="hljs-title" style="color: #ffc66d;">by</span> <span class="hljs-title" style="color: #ffc66d;">zero</span>
	<span class="hljs-title" style="color: #ffc66d;">at</span> <span class="hljs-title" style="color: #ffc66d;">section11_loose_ends</span>.<span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v2</span>.<span class="hljs-title" style="color: #ffc66d;">doSecondLevel</span>(<span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v2</span>.<span class="hljs-title" style="color: #ffc66d;">java</span>:13)
	<span class="hljs-title" style="color: #ffc66d;">at</span> <span class="hljs-title" style="color: #ffc66d;">section11_loose_ends</span>.<span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v2</span>.<span class="hljs-title" style="color: #ffc66d;">main</span>(<span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v2</span>.<span class="hljs-title" style="color: #ffc66d;">java</span>:5)

<span class="hljs-title" style="color: #ffc66d;">Process</span> <span class="hljs-title" style="color: #ffc66d;">finished</span> <span class="hljs-title" style="color: #ffc66d;">with</span> <span class="hljs-title" style="color: #ffc66d;">exit</span> <span class="hljs-title" style="color: #ffc66d;">code</span> 0</span></pre><p tabindex="-1" role="button" data-purpose="transcript-cue">So we got that familiar output, but then we got at exception tests that do second level exception test Java 13, and then we see another line here. Exception tests dot main. So what this is showing us is the tracing of the path that our thread took. A thread is just like this little guy who is actually stepping through each line of our program and executing those lines, and then he can jump to new lines as needed. So when our program is running, the thread will start at line to write and it'll it'll bring in, it'll carry in, so to speak, the any arguments that we passed in. Then it sees Line five do second level and it knows that this is a method call. So then the thread jumps down to the second level method and then it starts executing each of these lines.</p><p tabindex="-1" role="button" data-purpose="transcript-cue"><strong>Why are we seeing "you made it to the end" before we are seeing the stack trace?</strong></p><p tabindex="-1" role="button" data-purpose="transcript-cue">So just know that the way these stack traces are generated and the timing and order of the thread stuff, you should not expect that to print out in the exact order that you would intuitively assume it would. In this stack trace, we're seeing the most immediate method first. So it's kind of like the most recently called method will be at the top. So it's kind of backward to how a lot of people will tend to think. Intuitively you'll kind of start at the bottom. <strong>Typically, though, with a stack trace, the line of code where the exception occurred will be at the top.</strong></p><h2 id="mcetoc_1gb4uonu7ku" tabindex="-1" role="button" data-purpose="transcript-cue">Runtime Exceptions</h2><p tabindex="-1" role="button" data-purpose="transcript-cue">So far, we're looking at this array index out of bounds and the arithmetic exception. These two exceptions are actually both runtime exceptions, and that means that they don't actually have to be caught. As you already saw when we first started writing this, I'm going to just comment these out. Java is not forcing us to surround any of these lines with a try catch block.</p><p tabindex="-1" role="button" data-purpose="transcript-cue">And that is because of a couple of things. First off, the IDE and Java do not know at this point in time that either of these calls could result in an exception. It won't know that until runtime when we're actually running the the code. And that's one of the reasons why the type of exceptions that can be thrown from these kinds of errors are runtime exceptions. They can't easily be known before you start running. A human could analyze this particular code and see that we're passing a zero in and we're about to try to do a divide by zero. But the JVM can't really see it until you actually do it. And there's no guarantee that every time you divide by this variable that it's always going to be zero.</p><h2 id="mcetoc_1gb521do8qr" tabindex="-1" role="button" data-purpose="transcript-cue">Checked Exceptions</h2><p tabindex="-1" role="button" data-purpose="transcript-cue">Lets take for example that Code Snippet:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">            Long result = Files.lines(Path.of(<span class="hljs-string" style="color: #6a8759;">"/Users/Dave/Downloads/Hr5m.csv"</span>))</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">We know for a fact the creator of this method line's method knows that it is possible that the path that we are passing into it might not be a valid path. And because he or she knew at the time of writing this method that that could happen. They declared that this method is capable of throwing an IO exception and they made their IO exception class extend not from runtime exception, but directly from exception. And because it extends directly from exception, it is a checked exception, which means that we have to do something with it. And so what we're doing here is we're surrounding all of this code inside of a try catch block:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            <span class="hljs-keyword" style="color: #cc7832;">long</span> startTime = System.currentTimeMillis();
            Long result = Files.lines(Path.of(<span class="hljs-string" style="color: #6a8759;">"/Users/Dave/Downloads/Hr5m.csv"</span>))
                    .skip(<span class="hljs-number" style="color: #6897bb;">1</span>)
<span class="hljs-comment" style="color: grey;">//                    .limit(10)</span>
                    .map(s -&gt; s.split(<span class="hljs-string" style="color: #6a8759;">","</span>))
                    .map(arr -&gt; arr[<span class="hljs-number" style="color: #6897bb;">25</span>])
<span class="hljs-comment" style="color: grey;">//                    .forEach(System.out::println);</span>
                    .collect(Collectors.summingLong(sal -&gt; Long.parseLong(sal)));

            <span class="hljs-keyword" style="color: #cc7832;">long</span> endTime = System.currentTimeMillis();
<span class="hljs-comment" style="color: grey;">//            System.out.println(moneyFormat.format(result));</span>
            System.out.printf(<span class="hljs-string" style="color: #6a8759;">"$%,d.00%n"</span>, result);
            System.out.println(endTime - startTime + <span class="hljs-string" style="color: #6a8759;">"ms"</span>);
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (IOException e) {
            <span class="hljs-keyword" style="color: #cc7832;">throw</span> <span class="hljs-keyword" style="color: #cc7832;">new</span> RuntimeException(e);
        }
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">However, one other way that we could implement this is by adding the throws IOException at the end of the main Method signature:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v4</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> <span class="hljs-keyword" style="color: #cc7832;">throws</span> IOException </span>{
        Files.lines(Path.of(<span class="hljs-string" style="color: #6a8759;">"blababla"</span>));
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">This looks cleaner, right? But be careful with this. So now the main Method just declared to the JVM as a whole that, there is content that is capable of throwing an IO exception, but the main Method don't want to be the one to handle that. What so what I'm going to do is I'm going to take that particular exception if it is thrown and I'm going to re throw it back to whoever called me. So whatever code calls the main method, will have to handle whatever happens with this exception now. So we're kind of passing the buck on to the code that called this main method, which in this case is the JVM itself. And so the JVM is just going to blow up all the same. So in this particular case, I suppose you're not really losing much in such a simple program like this. However, imagine if we were writing a program with a user interface and we asked the user to select a file, right? Like it's a graphical program right in like a file open dialogue.</p><h2 id="mcetoc_1gb521do8qs" tabindex="-1" role="button" data-purpose="transcript-cue">Finally</h2><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">import</span> java.io.IOException;
<span class="hljs-keyword" style="color: #cc7832;">import</span> java.nio.file.Files;
<span class="hljs-keyword" style="color: #cc7832;">import</span> java.nio.file.Path;

<span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v4</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        <span class="hljs-keyword" style="color: #cc7832;">try</span> {
            Files.lines(Path.of(<span class="hljs-string" style="color: #6a8759;">"blababla"</span>));
        } <span class="hljs-keyword" style="color: #cc7832;">catch</span> (IOException e) {
            e.printStackTrace();
            System.out.println(<span class="hljs-string" style="color: #6a8759;">"We are unable to open the file"</span>);
        } <span class="hljs-keyword" style="color: #cc7832;">finally</span> {
            System.out.println(<span class="hljs-string" style="color: #6a8759;">"Make sure this runs no matter what..."</span>);
        }
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">output:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;">java.nio.file.NoSuchFileException: blababla
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:<span class="hljs-number" style="color: #6897bb;">92</span>)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:<span class="hljs-number" style="color: #6897bb;">106</span>)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:<span class="hljs-number" style="color: #6897bb;">111</span>)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:<span class="hljs-number" style="color: #6897bb;">181</span>)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:<span class="hljs-number" style="color: #6897bb;">298</span>)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:<span class="hljs-number" style="color: #6897bb;">357</span>)
	at java.base/java.nio.file.Files.lines(Files.java:<span class="hljs-number" style="color: #6897bb;">4132</span>)
	at java.base/java.nio.file.Files.lines(Files.java:<span class="hljs-number" style="color: #6897bb;">4227</span>)
	at section11_loose_ends.ExceptionTests_v4.main(ExceptionTests_v4.java:<span class="hljs-number" style="color: #6897bb;">10</span>)
We are unable to open the file
Make sure <span class="hljs-keyword" style="color: #cc7832;">this</span> runs no matter what...

Process finished with exit code <span class="hljs-number" style="color: #6897bb;">0</span></pre><p tabindex="-1" role="button" data-purpose="transcript-cue">So what's happening here is that sometimes depending on what you're trying to do inside of your try block, you may need to clean up or finish up some things before the program completely dies. Because as we've seen here, in many cases with a try catch block, the program is going to just die. Even though you may have that catch, you might be handling things in such a way that the program is still going to just die when it's done, but before it dies, you may want to clean a few things up.<br><br>One example of this would be in some kinds of applications where we might be opening files to read or write to them, or making connections to databases or things of that sort. If something goes wrong with any of those opening of connections and files and stuff, we don't want to just leave the file that we may have been able to open in in in a strange state. We want to ensure that even if something went wrong while we were reading data from somewhere, we still close that connection or closed that file gracefully and we can do that in a final block.<br><br>So what happens with the final block is that any code that we put here is strongly attempted by the JVM to be executed regardless of what went wrong in in the try in the try block.</p><h2 id="mcetoc_1gb521do8qt" tabindex="-1" role="button" data-purpose="transcript-cue">Optimizing the Example Szenarios</h2><p tabindex="-1" role="button" data-purpose="transcript-cue">What do we do to protect ourselves from this type of situation? And it's actually not that hard to protect ourselves from some of these situations in this particular. For example we could simply just make sure that num can not be zero and that the array length is not exceeded with if blocks:</p><pre class="hljs" style="color: #a9b7c6; background: #282b2e none repeat scroll 0% 0%; display: block; overflow-x: auto; padding: 0.5em;"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-class"><span class="hljs-keyword" style="color: #cc7832;">class</span> <span class="hljs-title" style="color: #ffc66d;">ExceptionTests_v5</span> </span>{
    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">public</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">main</span><span class="hljs-params">(String[] args)</span> </span>{
        doSecondLevel(<span class="hljs-number" style="color: #6897bb;">0</span>);
        System.out.println(<span class="hljs-string" style="color: #6a8759;">"You made it to the end"</span>);
    }

    <span class="hljs-function"><span class="hljs-keyword" style="color: #cc7832;">private</span> <span class="hljs-keyword" style="color: #cc7832;">static</span> <span class="hljs-keyword" style="color: #cc7832;">void</span> <span class="hljs-title" style="color: #ffc66d;">doSecondLevel</span><span class="hljs-params">(<span class="hljs-keyword" style="color: #cc7832;">int</span> num)</span> </span>{
        String[] array = {<span class="hljs-string" style="color: #6a8759;">"one"</span>, <span class="hljs-string" style="color: #6a8759;">"two"</span>, <span class="hljs-string" style="color: #6a8759;">"three"</span>};
        <span class="hljs-keyword" style="color: #cc7832;">if</span> (num != <span class="hljs-number" style="color: #6897bb;">0</span>) {
            System.out.println(array.length / num);
        }
        <span class="hljs-keyword" style="color: #cc7832;">int</span> index = <span class="hljs-number" style="color: #6897bb;">3</span>;
        <span class="hljs-keyword" style="color: #cc7832;">if</span> (index &lt; array.length) {
            System.out.println(array[<span class="hljs-number" style="color: #6897bb;">3</span>]);
        }
    }
}</pre><p tabindex="-1" role="button" data-purpose="transcript-cue">But please, don't put every line wrapped in some defensive if block. You got to try to find a balance.</p></div></div></div><footer class="wrapper post__footer"><p class="post__last-updated">This article was updated on August 23, 2022</p><ul class="post__tag"><li><a href="https://www.finecloud.ch/tags/dev/">dev</a></li><li><a href="https://www.finecloud.ch/tags/exception/">exception</a></li><li><a href="https://www.finecloud.ch/tags/exceptions/">exceptions</a></li><li><a href="https://www.finecloud.ch/tags/java/">java</a></li><li><a href="https://www.finecloud.ch/tags/java-basics/">java basics</a></li><li><a href="https://www.finecloud.ch/tags/softwareentwicklung/">software development</a></li><li><a href="https://www.finecloud.ch/tags/try-catch/">try catch</a></li></ul><div class="post__share"></div></footer></article><nav class="post__nav"><div class="post__nav-inner"><div class="post__nav-prev"><svg width="1.041em" height="0.416em" aria-hidden="true"><use xlink:href="https://www.finecloud.ch/assets/svg/svg-map.svg#arrow-prev"/></svg> <a href="https://www.finecloud.ch/visualisiere-deine-strava-aktivitaeten-mit-grafana.html" class="post__nav-link" rel="prev"><span>Previous</span> Visualisiere deine Strava AktivitÃ¤ten mit Grafana</a></div></div></nav><div class="post__related related"><div class="wrapper"><h2 class="h5 related__title">You should also read:</h2><article class="related__item"><div class="feed__meta"><time datetime="2022-05-26T14:07" class="feed__date">Mai 26, 2022</time></div><h3 class="h1"><a href="https://www.finecloud.ch/java-collection-iteratoren.html">Java Collection Iteratoren</a></h3></article><article class="related__item"><div class="feed__meta"><time datetime="2022-05-26T13:28" class="feed__date">Mai 26, 2022</time></div><h3 class="h1"><a href="https://www.finecloud.ch/java-collection-sets.html">Java Collection Sets</a></h3></article><article class="related__item"><div class="feed__meta"><time datetime="2022-05-26T13:19" class="feed__date">Mai 26, 2022</time></div><h3 class="h1"><a href="https://www.finecloud.ch/java-collection-listen.html">Java Collection Listen</a></h3></article></div></div></main><footer class="footer"><div class="footer__copyright"><p>Powered by Publii</p></div><button onclick="backToTopFunction()" id="backToTop" class="footer__bttop" aria-label="Back to top" title="Back to top"><svg><use xlink:href="https://www.finecloud.ch/assets/svg/svg-map.svg#toparrow"/></svg></button></footer></div><script>window.publiiThemeMenuConfig = {    
        mobileMenuMode: 'sidebar',
        animationSpeed: 300,
        submenuWidth: 'auto',
        doubleClickTime: 500,
        mobileMenuExpandableSubmenus: true, 
        relatedContainerForOverlayMenuSelector: '.top',
   };</script><script defer="defer" src="https://www.finecloud.ch/assets/js/scripts.min.js?v=6ca8b60e6534a3888de1205e82df8528"></script><script>var images = document.querySelectorAll('img[loading]');

        for (var i = 0; i < images.length; i++) {
            if (images[i].complete) {
                images[i].classList.add('is-loaded');
            } else {
                images[i].addEventListener('load', function () {
                    this.classList.add('is-loaded');
                }, false);
            }
        }</script></body></html>